export const MockListings = [
  {
    id: "1",
    title: "Handmade Ceramic Mug",
    description: "Beautifully glazed ceramic mug made by local artisan.",
    price: 18.99,
    category: "Home",
    sellerId: "user1",
    image: "/images/mug.jpg",
    createdAt: "2025-08-01",
  },
  {
    id: "2",
    title: "Freelance Logo Design",
    description: "Professional logo design service with 3-day delivery.",
    price: 75.0,
    category: "Design",
    sellerId: "user2",
    image: "/images/logo.jpg",
    createdAt: "2025-08-04",
  },
  {
    id: "3",
    title: "Used Mountain Bike",
    description: "Lightweight aluminum frame, barely used. Great condition.",
    price: 250,
    category: "Sports",
    sellerId: "user3",
    image: "/images/bike.jpg",
    createdAt: "2025-08-06",
  },
  {
    id: "4",
    title: "Digital Art Commission",
    description: "Custom character art in your preferred style. Fast turnaround!",
    price: 60,
    category: "Digital",
    sellerId: "user4",
    image: "/images/art.jpg",
    createdAt: "2025-08-03",
  },
];
